### ISSUE TITLE
Rewrite the project in Python

### ISSUE THREAD

**Issue by Arsh25** [thatrex/disphone-app#37]
**Is your feature request related to a problem? Please describe.**
Javascript was never meant to be used for any real work. It was a meme language and only designed to be used by pranksters who hated life and the world

**Describe the solution you'd like**
Move JavaScript back into the deep dark hole where it belongs. 

**Describe alternatives you've considered**
Literally anything else

**Additional context**

**Comment by Somekat** [comment]
yes

**Comment by verumIgnis** [comment]
Everything that can be written in javascript sadly has been written in javascript.
